name: Build and deploy ASP.Net Core app to Azure Web App - RedisWeb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build redis.WebAPi/redis.WebAPi.csproj --configuration Release

      - name: Publish with dotnet
        run: dotnet publish redis.WebAPi/redis.WebAPi.csproj -c Release -o ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: net-app       # 去掉开头的点
          path: ./myapp       # 指向 publish 输出目录

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: net-app       # 和上传一致
      
      - name: Login to Azure using Managed Identity
        uses: azure/login@v2
        with:
          auth-type: managedidentity

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'RedisWeb'
          slot-name: 'Production'
          package: ./myapp   # 指向下载下来的 artifact


